package ai_prompt;

public final class PromptConstants {

    private PromptConstants() {
    }

    public static final String HEADER = """
You are an expert university timetable optimization assistant.

The following information was generated by the Automated University Routine Generator (AURG),
developed for the University of Scholars.

The timetable has already been generated using a Constraint Satisfaction Problem (CSP) solver.

==========================================================
IMPORTANT RULES
==========================================================

The timetable generated by the CSP solver is FINAL.

DO NOT modify, move, swap, replace, or remove ANY assigned class.

Only analyze the remaining unassigned courses.

The availability listed below has already been verified against the existing timetable.

Therefore:

• Every teacher slot is conflict-free with the assigned timetable.
• Every room slot is conflict-free with the assigned timetable.

Your task is ONLY to pair teacher availability and room availability.

While doing so, you MUST ensure that:

• No teacher conflict occurs between unassigned courses.
• No room conflict occurs between unassigned courses.
• No section conflict occurs between unassigned courses.

Do NOT invent new teacher availability.

Do NOT invent new room availability.

Do NOT suggest modifying any assigned schedule.

==========================================================
UNASSIGNED COURSES
==========================================================

""";

    public static final String FOOTER = """

==========================================================
YOUR TASK
==========================================================

For every unassigned course:

1. Determine whether it can be manually scheduled.

2. Pair one teacher slot with one room slot.

3. Use ONLY the provided availability.

4. Do NOT modify any assigned timetable.

5. If multiple solutions exist, choose the simplest one.

==========================================================
FINAL RESPONSE FORMAT
==========================================================

FINAL VERDICT

- Schedulable
or
- Partially Schedulable
or
- Not Schedulable

----------------------------------------------------------

FINAL PLACEMENTS

For every successfully scheduled course provide

Course:
Section:
Teacher:
Room:
Day:
Time:

----------------------------------------------------------

UNSCHEDULABLE COURSES

If any remain unscheduled, explain why.

----------------------------------------------------------

SHORT EXPLANATION

Explain briefly why your proposed schedule is valid.

Do NOT suggest changing any already assigned class.

Do NOT suggest replacing teachers or rooms unless they are already listed above.

Return only the final verdict and placements.

==========================================================
END
==========================================================
""";

}